[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "pydentity-db-tortoise"
version = "1.0.0"
dependencies = [
    "tortoise-orm>=0.21.5"
]

[tool.setuptools.packages.find]
exclude = [
    "tests*",
    "examples*"
]
